name: Deploy update to server

on:
  push:
      branches: [ main ]

jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote ssh commands using ssh key passphrase
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                port: 22
                script: |
                  cd Atom-Query-Discord-Bot
                  git pull origin main
                  pm2 restart bot.py --update-env --interpreter=/usr/bin/python3