name: Deploy update to server

on:
  
  push:
      
      branches: [ main ]

jobs:

    build:

        name: Deploy
        runs-on: ubuntu-latest

        steps:

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:

                host: ${{ secrets.HOST }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
                port: 22
                script: |

                  cd Atom-Query-Discord-Bot
                  git pull origin main
                  pm2 stop bot.py
                  pm2 start bot.py --interpreter=/usr/bin/python3
